USE TOKAS;
WHILE(EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'))
BEGIN
    DECLARE @sql NVARCHAR(2000)
    SELECT TOP 1 @sql=('ALTER TABLE ' + TABLE_SCHEMA + '.[' + TABLE_NAME + '] DROP CONSTRAINT [' + CONSTRAINT_NAME + ']')
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
    EXEC(@sql)
END
WHILE(EXISTS(SELECT 1 FROM sys.tables))
BEGIN
    DECLARE @sqlDrop NVARCHAR(2000)
    SELECT TOP 1 @sqlDrop=('DROP TABLE [' + SCHEMA_NAME(schema_id) + '].[' + name + ']')
    FROM sys.tables
    EXEC(@sqlDrop)
END
